import type { Product, Brand, Testimonial, ScienceConcept, Certification } from '@/lib/types';
import { PlaceHolderImages } from './placeholder-images';

const getImageUrl = (id: string) => PlaceHolderImages.find(p => p.id === id)?.imageUrl;

export const placeholderData: {
  products: Product[];
  brands: Brand[];
  testimonials: Testimonial[];
  scienceConcepts: ScienceConcept[];
  certifications: Certification[];
} = {
  products: [
    {
      id: 'p1',
      name: 'Aqua-Ionizer Deluxe 9.0',
      brand: 'Life Ionizers',
      price: 149000,
      imageId: 'product-1',
      imageGallery: ['product-1', 'product-2', 'product-3', 'product-4'],
      description: 'Top-of-the-line model with 9 plates and a wide pH range.',
      specs: { phRange: '2.5-11.5', orpRange: '+600 to -860mV', plates: '9 Titanium Platinum-Coated' },
    },
    {
      id: 'p2',
      name: 'KYK Generation II',
      brand: 'KYK',
      price: 125000,
      imageId: 'product-2',
      imageGallery: ['product-2', 'product-3', 'product-4', 'product-1'],
      description: 'A reliable and efficient ionizer for modern kitchens.',
      specs: { phRange: '4.0-10.0', orpRange: '+500 to -400mV', plates: '7 Titanium Platinum-Coated' },
    },
    {
      id: 'p3',
      name: 'Tyent UCE-11',
      brand: 'Tyent',
      price: 249000,
      imageId: 'product-3',
      imageGallery: ['product-3', 'product-4', 'product-1', 'product-2'],
      description: 'Under-counter model with 11 plates for maximum power.',
      specs: { phRange: '1.7-12.0', orpRange: '+900 to -1050mV', plates: '11 Solid/Mesh Hybrid' },
    },
    {
      id: 'p4',
      name: 'Enagic K8',
      brand: 'Enagic',
      price: 298000,
      imageId: 'product-4',
      imageGallery: ['product-4', 'product-1', 'product-2', 'product-3'],
      description: 'The mighty 8-plate anti-oxidizer for powerful, fresh, and delicious water.',
      specs: { phRange: '2.5-11.5', orpRange: '+1130mV to -800mV', plates: '8 Titanium Platinum-Coated' },
    },
    {
      id: 'p5',
      name: 'Alkamedi 3000S',
      brand: 'Alkamedi',
      price: 95000,
      imageId: 'product-5',
      imageGallery: ['product-5', 'product-6', 'product-7', 'product-8'],
      description: 'A great balance of features and affordability for any home.',
      specs: { phRange: '3.5-10.0', orpRange: '+500mV to -450mV', plates: '5 Titanium Platinum-Coated' },
    },
    {
      id: 'p6',
      name: 'ZeroB Eco-Ionizer',
      brand: 'ZeroB',
      price: 75000,
      imageId: 'product-6',
      imageGallery: ['product-6', 'product-7', 'product-8', 'product-5'],
      description: 'Compact and eco-friendly ionizer, perfect for smaller kitchens.',
      specs: { phRange: '4.5-9.5', orpRange: '+400mV to -300mV', plates: '5 Titanium Platinum-Coated' },
    },
    {
      id: 'p7',
      name: 'Medisoul Genesis Plus',
      brand: 'Medisoul',
      price: 115000,
      imageId: 'product-7',
      imageGallery: ['product-7', 'product-8', 'product-5', 'product-6'],
      description: 'Advanced filtration and ionization for health-conscious families.',
      specs: { phRange: '3.0-11.0', orpRange: '+600mV to -500mV', plates: '7 Titanium Platinum-Coated' },
    },
    {
      id: 'p8',
      name: 'Life Ionizer M13',
      brand: 'Life Ionizers',
      price: 349000,
      imageId: 'product-8',
      imageGallery: ['product-8', 'product-5', 'product-6', 'product-7'],
      description: 'The world\'s most powerful home water ionizer with 13 plates.',
      specs: { phRange: '1.7-12.2', orpRange: '+900mV to -1200mV', plates: '13 Titanium Platinum-Coated' },
    },
    {
      id: 'p9',
      name: 'Aqua-Ionizer Pro 7.5',
      brand: 'KYK',
      price: 135000,
      imageId: 'product-9',
      imageGallery: ['product-9', 'product-10', 'product-11', 'product-12'],
      description: 'A professional-grade ionizer with 7 plates and enhanced user controls.',
      specs: { phRange: '2.7-11.0', orpRange: '+550 to -800mV', plates: '7 Titanium Platinum-Coated' },
    },
    {
      id: 'p10',
      name: 'Tyent ACE-13',
      brand: 'Tyent',
      price: 285000,
      imageId: 'product-10',
      imageGallery: ['product-10', 'product-11', 'product-12', 'product-9'],
      description: 'Above-counter elegance with 13 plates for ultimate water purity.',
      specs: { phRange: '1.7-12.0', orpRange: '+900 to -1150mV', plates: '13 Solid/Mesh Hybrid' },
    },
    {
      id: 'p11',
      name: 'Enagic Leveluk SD501',
      brand: 'Enagic',
      price: 270000,
      imageId: 'product-11',
      imageGallery: ['product-11', 'product-12', 'product-9', 'product-10'],
      description: 'The industry gold standard for high-quality ionized water.',
      specs: { phRange: '2.5-11.5', orpRange: '+1130mV to -800mV', plates: '7 Titanium Platinum-Coated' },
    },
    {
      id: 'p12',
      name: 'Alkamedi 5000',
      brand: 'Alkamedi',
      price: 110000,
      imageId: 'product-12',
      imageGallery: ['product-12', 'product-9', 'product-10', 'product-11'],
      description: 'Sleek design meets powerful performance with 5 advanced plates.',
      specs: { phRange: '3.0-10.5', orpRange: '+450mV to -500mV', plates: '5 Titanium Platinum-Coated' },
    },
    {
      id: 'p13',
      name: 'Life Ionizer M9',
      brand: 'Life Ionizers',
      price: 210000,
      imageId: 'product-13',
      imageGallery: ['product-13', 'product-14', 'product-15', 'product-16'],
      description: 'A powerful 9-plate system for superior antioxidant-rich water.',
      specs: { phRange: '2.0-11.8', orpRange: '+700mV to -900mV', plates: '9 Titanium Platinum-Coated' },
    },
    {
      id: 'p14',
      name: 'ZeroB Ion-Max',
      brand: 'ZeroB',
      price: 85000,
      imageId: 'product-14',
      imageGallery: ['product-14', 'product-15', 'product-16', 'product-13'],
      description: 'Maximum ionization in a compact form factor for Indian homes.',
      specs: { phRange: '4.0-10.0', orpRange: '+350mV to -350mV', plates: '5 Titanium Platinum-Coated' },
    },
    {
      id: 'p15',
      name: 'Medisoul Aqua Prime',
      brand: 'Medisoul',
      price: 130000,
      imageId: 'product-15',
      imageGallery: ['product-15', 'product-16', 'product-13', 'product-14'],
      description: 'Prime your health with this advanced 7-plate water ionizer.',
      specs: { phRange: '3.0-11.2', orpRange: '+500mV to -600mV', plates: '7 Titanium Platinum-Coated' },
    },
    {
      id: 'p16',
      name: 'KYK Harmony',
      brand: 'KYK',
      price: 105000,
      imageId: 'product-16',
      imageGallery: ['product-16', 'product-13', 'product-14', 'product-15'],
      description: 'Find your body\'s perfect balance with this harmonious water ionizer.',
      specs: { phRange: '4.5-9.8', orpRange: '+400mV to -380mV', plates: '5 Titanium Platinum-Coated' },
    },
    {
      id: 'p17',
      name: 'Tyent Edge 9000T',
      brand: 'Tyent',
      price: 195000,
      imageId: 'product-17',
      imageGallery: ['product-17', 'product-18', 'product-19', 'product-20'],
      description: 'A cutting-edge countertop model with 9 turbocharged plates.',
      specs: { phRange: '2.0-12.0', orpRange: '+800mV to -1000mV', plates: '9 Solid/Mesh Hybrid' },
    },
    {
      id: 'p18',
      name: 'Enagic JRIV',
      brand: 'Enagic',
      price: 180000,
      imageId: 'product-18',
      imageGallery: ['product-18', 'product-19', 'product-20', 'product-17'],
      description: 'The Junior Model with four plates, perfect for singles or couples.',
      specs: { phRange: '2.5-11.5', orpRange: '+1130mV to -450mV', plates: '4 Titanium Platinum-Coated' },
    },
    {
      id: 'p19',
      name: 'Life Ionizer M5',
      brand: 'Life Ionizers',
      price: 105000,
      imageId: 'product-19',
      imageGallery: ['product-19', 'product-20', 'product-17', 'product-18'],
      description: 'An affordable entry into high-quality ionized water with 5 plates.',
      specs: { phRange: '4.0-10.0', orpRange: '+600mV to -500mV', plates: '5 Titanium Platinum-Coated' },
    },
    {
      id: 'p20',
      name: 'Alkamedi 7000',
      brand: 'Alkamedi',
      price: 155000,
      imageId: 'product-20',
      imageGallery: ['product-20', 'product-17', 'product-18', 'product-19'],
      description: 'A premium 7-plate ionizer with a user-friendly interface.',
      specs: { phRange: '3.0-11.0', orpRange: '+500mV to -700mV', plates: '7 Titanium Platinum-Coated' },
    },
    {
      id: 'p21',
      name: 'ZeroB Alkaline Craze',
      brand: 'ZeroB',
      price: 65000,
      imageId: 'product-21',
      imageGallery: ['product-21', 'product-22', 'product-23', 'product-24'],
      description: 'Join the craze for alkaline water with this entry-level ionizer.',
      specs: { phRange: '5.0-9.0', orpRange: '+300mV to -250mV', plates: '3 Titanium Platinum-Coated' },
    },
    {
      id: 'p22',
      name: 'Medisoul Genesis Pro',
      brand: 'Medisoul',
      price: 160000,
      imageId: 'product-22',
      imageGallery: ['product-22', 'product-23', 'product-24', 'product-21'],
      description: 'Professional grade ionization with 9 plates for maximum benefits.',
      specs: { phRange: '2.8-11.5', orpRange: '+650mV to -800mV', plates: '9 Titanium Platinum-Coated' },
    },
    {
      id: 'p23',
      name: 'KYK Generation 3',
      brand: 'KYK',
      price: 185000,
      imageId: 'product-23',
      imageGallery: ['product-23', 'product-24', 'product-21', 'product-22'],
      description: 'The latest generation with improved filtration and 9 plates.',
      specs: { phRange: '2.5-11.5', orpRange: '+600mV to -850mV', plates: '9 Titanium Platinum-Coated' },
    },
    {
      id: 'p24',
      name: 'Tyent H2 Hybrid',
      brand: 'Tyent',
      price: 320000,
      imageId: 'product-24',
      imageGallery: ['product-24', 'product-21', 'product-22', 'product-23'],
      description: 'A unique hybrid ionizer and hydrogen generator for peak wellness.',
      specs: { phRange: '1.7-12.0', orpRange: '+900mV to -1200mV', plates: '11 Solid/Mesh Hybrid' },
    },
    {
      id: 'p25',
      name: 'Enagic Super 501',
      brand: 'Enagic',
      price: 397000,
      imageId: 'product-25',
      imageGallery: ['product-25', 'product-26', 'product-27', 'product-28'],
      description: 'The ultimate ionizer for heavy home use, with 12 plates.',
      specs: { phRange: '2.5-11.5', orpRange: '+1130mV to -800mV', plates: '12 Titanium Platinum-Coated' },
    },
    {
      id: 'p26',
      name: 'Life Ionizer Stream',
      brand: 'Life Ionizers',
      price: 89000,
      imageId: 'product-26',
      imageGallery: ['product-26', 'product-27', 'product-28', 'product-25'],
      description: 'A compact, stylish, and affordable streaming water ionizer.',
      specs: { phRange: '4.5-9.5', orpRange: '+500mV to -400mV', plates: '5 Titanium Platinum-Coated' },
    },
    {
      id: 'p27',
      name: 'Alkamedi LITE',
      brand: 'Alkamedi',
      price: 70000,
      imageId: 'product-27',
      imageGallery: ['product-27', 'product-28', 'product-25', 'product-26'],
      description: 'A lightweight and simple ionizer for daily hydration needs.',
      specs: { phRange: '4.5-9.5', orpRange: '+400mV to -300mV', plates: '3 Titanium Platinum-Coated' },
    },
    {
      id: 'p28',
      name: 'Medisoul Aqua Atom',
      brand: 'Medisoul',
      price: 99000,
      imageId: 'product-28',
      imageGallery: ['product-28', 'product-25', 'product-26', 'product-27'],
      description: 'Atomic power in a small package, this 5-plate ionizer is a powerhouse.',
      specs: { phRange: '3.5-10.5', orpRange: '+550mV to -450mV', plates: '5 Titanium Platinum-Coated' },
    }
  ],
  brands: [
    { id: 'b1', name: 'Life Ionizers', logoId: 'brand-life-ionizers', logoUrl: getImageUrl('brand-life-ionizers'), description: 'Life Ionizers is a leading manufacturer of water ionizers, known for their powerful machines and lifetime warranties.' },
    { id: 'b2', name: 'Mediqua', logoId: 'brand-mediqua', logoUrl: getImageUrl('brand-mediqua'), description: 'Mediqua focuses on creating medical-grade water ionizers with advanced filtration systems for the purest water.' },
    { id: 'b3', name: 'KYK', logoId: 'brand-kyk', logoUrl: getImageUrl('brand-kyk'), description: 'KYK is a renowned Korean brand that has been developing top-quality water ionizers for over 25 years.' },
    { id: 'b4', name: 'Enagic', logoId: 'brand-enagic', logoUrl: getImageUrl('brand-enagic'), description: 'Enagic is a global leader in water ionization systems, famous for their Kangen Water® machines and direct sales model.' },
    { id: 'b5', name: 'Tyent', logoId: 'brand-tyent', logoUrl: getImageUrl('brand-tyent'), description: 'Tyent is known for its stylish and technologically advanced ionizers, often featuring large touchscreens and hybrid plates.' },
    { id: 'b6', name: 'Alkamedi', logoId: 'brand-alkamedi', logoUrl: getImageUrl('brand-alkamedi'), description: 'Alkamedi offers a range of reliable and affordable water ionizers, balancing performance with cost-effectiveness.' },
    { id: 'b7', name: 'ZeroB', logoId: 'brand-zerob', logoUrl: getImageUrl('brand-zerob'), description: 'ZeroB is an Indian brand that provides a variety of water purification solutions, including ionizers designed for local water conditions.' },
    { id: 'b8', name: 'Medisoul', logoId: 'brand-medisoul', logoUrl: getImageUrl('brand-medisoul'), description: 'Medisoul is committed to providing health and wellness products, with a focus on advanced water ionization technology for Indian consumers.' },
  ],
  testimonials: [
    {
      id: 't1',
      name: 'Rohan Sharma',
      location: 'Mumbai, India',
      avatarId: 'testimonial-1',
      quote: 'Since using the water ionizer from Ionora, I feel more energetic and hydrated. The customer support was excellent!',
    },
    {
      id: 't2',
      name: 'Priya Desai',
      location: 'Bangalore, India',
      avatarId: 'testimonial-2',
      quote: 'I was skeptical at first, but the difference in water taste and quality is undeniable. The comparison tool helped me choose.',
    },
    {
      id: 't3',
      name: 'Amit Patel',
      location: 'Ahmedabad, India',
      avatarId: 'testimonial-3',
      quote: 'As a health-conscious person, I appreciate the detailed scientific information. It helped me understand the benefits.',
    },
    {
      id: 't4',
      name: 'Sunita Nair',
      location: 'Chennai, India',
      avatarId: 'testimonial-4',
      quote: 'The financing options made it easy to purchase a top-tier model. My skin has never looked better!',
    },
    {
      id: 't5',
      name: 'Vikram Singh',
      location: 'Delhi, India',
      avatarId: 'testimonial-5',
      quote: 'Great selection of brands all in one place. The product pages have all the specs you need to make an informed choice.',
    },
    {
      id: 't6',
      name: 'Anjali Rao',
      location: 'Hyderabad, India',
      avatarId: 'testimonial-6',
      quote: 'Ionora is the best place to buy a water ionizer in India. Fast delivery and professional installation.',
    },
  ],
  scienceConcepts: [
    {
      id: 'sc1',
      title: 'Electrolysis',
      description: 'The process of using electricity to separate water into alkaline and acidic components.',
      icon: 'ElectrolysisIcon',
      concept: 'Electrolysis'
    },
    {
      id: 'sc2',
      title: 'Understanding ORP',
      description: 'A measure of water\'s ability to act as an antioxidant.',
      icon: 'OrpIcon',
      concept: 'ORP (Oxidation-Reduction Potential)'
    },
    {
      id: 'sc3',
      title: 'The pH Scale',
      description: 'Learn how water is measured as alkaline or acidic.',
      icon: 'PhScaleIcon',
      concept: 'The pH Scale & Alkalinity'
    },
    {
      id: 'sc4',
      title: 'Microclustering',
      description: 'How ionized water may be more easily absorbed by the body.',
      icon: 'MicroclusteringIcon',
      concept: 'Microclustering'
    },
    {
        id: 'sc5',
        title: 'Hydrogen-Rich Water',
        description: 'Discover the therapeutic potential of molecular hydrogen.',
        icon: 'HydrogenIcon',
        concept: 'Hydrogen-Rich Water'
      },
  ],
  certifications: [
    {
      id: 'cert1',
      title: 'ISO 9001',
      imageId: 'cert-iso-9001'
    },
    {
      id: 'cert2',
      title: 'CE Certified',
      imageId: 'cert-ce'
    },
    {
      id: 'cert3',
      title: 'Water Quality Association',
      imageId: 'cert-wqa'
    },
    {
      id: 'cert4',
      title: 'RoHS Compliant',
      imageId: 'cert-rohs'
    }
  ],
};
